# Generated by Django 4.0 on 2024-03-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    #constructors for the countries
    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    #essentially constructors for different delegates
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('streedAddr', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('stateId', models.IntegerField()),
                ('zip', models.IntegerField()),
                ('mobilePhone', models.CharField(max_length=15)),
                ('grade', models.SmallIntegerField()),
                ('parentName', models.CharField(max_length=50)),
                ('parentEmail', models.CharField(max_length=100)),
                ('raceId', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('yearAtMun', models.SmallIntegerField()),
            ],
        ),
        #constructors for delegation
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegateId1', models.IntegerField()),
                ('delegateId2', models.IntegerField()),
                ('delegateId3', models.IntegerField()),
                ('delegateId4', models.IntegerField()),
            ],
        ),
        #constructors for race
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=30)),
            ],
        ),
        #constructor for model
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegationId', models.SmallIntegerField()),
                ('countryId', models.SmallIntegerField()),
            ],
        ),
        #constructors states
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateNameLong', models.CharField(max_length=20)),
                ('stateNameShort', models.CharField(max_length=2)),
            ],
        ),
    ]
