# Generated by Django 4.0 on 2024-03-23 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registry_choicerank_registry_registry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='registry',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 23, 22, 29, 41, 326423), editable=False),
        ),
    ]
