# Generated by Django 4.0 on 2024-03-26 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_remove_delegation_delegateid1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='assignedCountryID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registration.country'),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='schoolId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registration.school'),
        ),
        migrations.AlterField(
            model_name='team',
            name='schoolId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registration.school'),
        ),
    ]
