# Generated by Django 4.0 on 2024-03-27 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_rename_raceid_delegate_race_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delegate',
            old_name='schoolId',
            new_name='school',
        ),
        migrations.AddField(
            model_name='team',
            name='country1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='country1', to='registration.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='country10',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='country10', to='registration.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='country2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='country2', to='registration.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='country3',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='country3', to='registration.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='country4',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='country4', to='registration.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='country5',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='country5', to='registration.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='country6',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='country6', to='registration.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='country7',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='country7', to='registration.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='country8',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='country8', to='registration.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='country9',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='country9', to='registration.country'),
            preserve_default=False,
        ),
    ]
