# Generated by Django 4.0 on 2024-03-27 01:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_rename_schoolid_delegate_school_team_country1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delegate',
            old_name='streedAddr',
            new_name='streetAddr',
        ),
        migrations.AddField(
            model_name='delegate',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 27, 1, 53, 48, 131779, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delegation',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.school'),
        ),
        migrations.AlterField(
            model_name='team',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.school'),
        ),
    ]
