# Generated by Django 4.0 on 2024-03-28 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_delegate_parentphone_alter_delegate_yearatmun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='country1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='country10',
        ),
        migrations.RemoveField(
            model_name='team',
            name='country2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='country3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='country4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='country5',
        ),
        migrations.RemoveField(
            model_name='team',
            name='country6',
        ),
        migrations.RemoveField(
            model_name='team',
            name='country7',
        ),
        migrations.RemoveField(
            model_name='team',
            name='country8',
        ),
        migrations.RemoveField(
            model_name='team',
            name='country9',
        ),
        migrations.AlterField(
            model_name='team',
            name='delegate2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegate2', to='registration.delegate'),
        ),
        migrations.AlterField(
            model_name='team',
            name='delegate3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegate3', to='registration.delegate'),
        ),
        migrations.AlterField(
            model_name='team',
            name='delegate4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegate4', to='registration.delegate'),
        ),
    ]
