# Generated by Django 4.0 on 2024-03-29 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_remove_team_country1_remove_team_country10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegate',
            name='role',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='assignedCountry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registration.country'),
        ),
    ]
