# Generated by Django 4.0 on 2024-03-31 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('registration', '0014_advisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', unique=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.team', unique=True),
        ),
    ]
